# make sure to install yaml package using install.packages("yaml") if not installed already

sandbox_dir  : "/Users/peterlafollette/CIROH_project/NextGenSandboxHub"
input_dir     : "/Users/peterlafollette/CIROH_project/in"  # user-specified
output_dir    : "/Users/peterlafollette/CIROH_project/model1/out" # user-specified


########################################################################
# Subset a basin using hydrofabric; see src/R/main.R for further details
subsetting :
  hf_version               : "2.1.1" # Only enter version number, e.g. "2.2" or "2.1.1"
  # Ensure that this gpkg matches the hf_version specified above:
  hf_gpkg_path             : "/Users/peterlafollette/CIROH_project/conus_nextgen.gpkg"  #for example, "<paht_to>/conus_nextgen.gpkg" # input
  dem_output_dir           : "/Users/peterlafollette/CIROH_project/in/dem" # create `dem` directory yourself # output
  number_processors        : 1
  compute_divide_attributes: true #necessary if using hydrofabric v 2.1.1, will cause an error if using hydrofabric v 2.2

  # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
  options :
    use_gage_id :
      use_gage_id  : FALSE
      gage_ids     : "01105000" #for instance, ["01105000"]
    use_gage_file :
      use_gage_file : TRUE
      gage_file     : "/Users/peterlafollette/CIROH_project/NextGenSandboxHub/basin_IDs/basin_IDs.csv"
      column_name   : "gage_id"
    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"

########################################################################
#forcing data is stored under <input_dir>/gage_id/data/forcing
forcings : 
  forcing_format     : ".nc"
  forcing_time       : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2024-09-30 23:00:00"}

########################################################################
formulation :
  ngen_dir           : "/Users/peterlafollette/CIROH_project/ngen" # for instance, /Users/ajkhattak/codes/ngen_repo/ngen"
  # models             : "NOM, CFE, T-route"
  models             : "PET, LASAM, T-route"

  clean              : ['existing']
  verbosity          : 0

  np_per_basin           : 1         # number of processors for basin partitioning
  np_per_basin_adaptive  : False     # adaptive - set by the workflow
  basins_in_par          : 1         # use for both config files and simulations

simulation :
  task_type : "control" # calibvalid, calibration, validation, restart, control
  simulation_time  : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}
  # simulation_time  : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2013-09-30 23:00:00"}
  calibration_time : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}
  calib_eval_time  : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}
  validation_time  : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}
  valid_eval_time  : {"start_time" : "2010-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}
  restart_dir      : "<path_to_restart_dir>/{*}/202410042024_ngen_qaiklwj0_worker/" # TODO
  
